let data = [
    {
        id: 1,
        address: 'London',
        starts: 1,
        note: '',
        photo: null,
        date: '28.01.20',
        time: '17.10',
        reaction: null,
    },
    {
        id: 2,
        address: 'Paris',
        starts: 4,
        note: 'good',
        photo: null,
        date: '15.03.19',
        time: '10.12',
        reaction: null,
    },
    {
        id: 3,
        address: 'New-York',
        starts: 5,
        note: 'great',
        photo: null,
        date: '12.10.20',
        time: '12.42',
        reaction: null,
    },
    {
        id: 4,
        address: 'Berlin',
        starts: 5,
        note: 'great',
        photo: null,
        date: '12.10.20',
        time: '18.42',
        reaction: null,
    },
    {
        id: 5,
        address: 'Kyiv',
        starts: 5,
        note: 'great',
        photo: null,
        date: '12.10.20',
        time: '14.42',
        reaction: null,
    },
    {
        id: 6,
        address: 'Lvov',
        starts: 5,
        note: 'great',
        photo: null,
        date: '13.12.18',
        time: '15.32',
        reaction: null,
    },
    {
        id: 7,
        address: 'Odesa',
        starts: 4,
        note: '',
        photo: null,
        date: '18.04.15',
        time: '16.22',
        reaction: null,
    },
    {
        id: 8,
        address: 'Madrid',
        starts: 3,
        note: '',
        photo: null,
        date: '18.04.17',
        time: '08.22',
        reaction: null,
    },
    {
        id: 9,
        address: 'Madrid',
        starts: 3,
        note: '',
        photo: null,
        date: '18.04.17',
        time: '04.56',
        reaction: null,
    },
];
export default data;